Fix CI: cannot assume role (#99)
The deployment is failing with following message[1]

Error: Could not assume role with OIDC:
Not authorized to perform sts:AssumeRoleWithWebIdentity

Not sure why it's failing but the similar CI setup for agora-infra-v3[2]
works so attempting to fix with a refactor to the same setup.

[1] https://github.com/Sage-Bionetworks-IT/openchallenges/actions/runs/13117959589/job/36596798361
[2] https://github.com/Sage-Bionetworks-IT/agora-infra-v3/actions